

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.MimetypesFileTypeMap;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC Master Race
 */
public class allStudents extends javax.swing.JFrame {

    
    public java.sql.Connection veza;
    database db;
    String imagePath = null;
    
    /**
     * Creates new form allStudents
     */
    public allStudents() {
        initComponents();
        this.setLocationRelativeTo(null);
        db = new database();
        db.initConnection_MySQL();
        populateJTable();
        Color greenish = new Color(11,19,43);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(greenish);
        jTable1.setSelectionBackground(Color.lightGray);
        jTable1.setFont(new Font("Monaco", Font.BOLD, 20));
        if(jComboBox2.getSelectedIndex() == 0){
            jButton6.setEnabled(false);
        }
        
        
        JTableHeader th = jTable1.getTableHeader();       
        th.setForeground(Color.BLACK);  
        
        th.setFont(new Font("Tahoma",Font.PLAIN,16) {
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabelClose1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelUserPic = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextFieldSearchSurname1 = new javax.swing.JTextField();
        jTextFieldSearchName1 = new javax.swing.JTextField();
        jLabelSName5 = new javax.swing.JLabel();
        jLabelSName8 = new javax.swing.JLabel();
        jLabelSName7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1220, 730));

        jPanel1.setBackground(new java.awt.Color(11, 19, 43));

        jLabelClose1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelClose1.setForeground(new java.awt.Color(102, 102, 102));
        jLabelClose1.setText("X");
        jLabelClose1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose1MouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(111, 255, 233));
        jLabel4.setText("STUDENTI");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("-");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabelUsername.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(111, 255, 233));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelUserPic, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsername)
                .addGap(396, 396, 396)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose1)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelClose1)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabelUsername)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelUserPic, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(58, 80, 107));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField5.setBackground(new java.awt.Color(11, 19, 43));
        jTextField5.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(111, 255, 233));
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 104, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(111, 255, 233));
        jLabel9.setText("Datum Rođenja:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, -1, -1));

        jTextField1.setBackground(new java.awt.Color(11, 19, 43));
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(111, 255, 233));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 17, 104, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(111, 255, 233));
        jLabel10.setText("Godina:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(111, 255, 233));
        jLabel3.setText("Ime:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 20, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(11, 19, 43));
        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(111, 255, 233));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1", "2", "3" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 104, -1));

        jTextField2.setBackground(new java.awt.Color(11, 19, 43));
        jTextField2.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(111, 255, 233));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 68, 104, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(111, 255, 233));
        jLabel6.setText("Prezime:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 71, -1, -1));

        jTextField3.setBackground(new java.awt.Color(11, 19, 43));
        jTextField3.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(111, 255, 233));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 112, 104, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(111, 255, 233));
        jLabel7.setText("Adresa:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 115, -1, -1));

        jTextField4.setBackground(new java.awt.Color(11, 19, 43));
        jTextField4.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(111, 255, 233));
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 104, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(111, 255, 233));
        jLabel8.setText("Fakultet:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(111, 255, 233));
        jLabel11.setText("Slika:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(966, 30, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1022, 36, 162, 132));

        jTable1.setBackground(new java.awt.Color(58, 80, 107));
        jTable1.setForeground(new java.awt.Color(111, 255, 233));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(111, 255, 233));
        jTable1.setSelectionBackground(new java.awt.Color(11, 19, 43));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 298, 1184, 358));

        jTextArea1.setBackground(new java.awt.Color(11, 19, 43));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(111, 255, 233));
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 219, 491, 61));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(111, 255, 233));
        jLabel12.setText("Status:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 193, -1, -1));

        jButton3.setBackground(new java.awt.Color(111, 255, 233));
        jButton3.setForeground(new java.awt.Color(60, 63, 65));
        jButton3.setText("ODABIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 180, -1, -1));

        jButton4.setBackground(new java.awt.Color(111, 255, 233));
        jButton4.setForeground(new java.awt.Color(60, 63, 65));
        jButton4.setText("SPREMI PROMJENE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 220, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(111, 255, 233));
        jLabel13.setText("Id:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, -1, -1));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(11, 19, 43));
        jTextField6.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(111, 255, 233));
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 104, -1));

        jButton5.setBackground(new java.awt.Color(111, 255, 233));
        jButton5.setForeground(new java.awt.Color(60, 63, 65));
        jButton5.setText("IZBRIŠI STUDENTA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 250, -1, -1));

        jButton6.setBackground(new java.awt.Color(111, 255, 233));
        jButton6.setForeground(new java.awt.Color(60, 63, 65));
        jButton6.setText("PRETRAGA");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 158, -1, -1));

        jComboBox2.setBackground(new java.awt.Color(111, 255, 233));
        jComboBox2.setForeground(new java.awt.Color(11, 19, 43));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Svi studenti", "Ime", "Prezime", "Ime i Prezime" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 159, 128, -1));

        jTextFieldSearchSurname1.setBackground(new java.awt.Color(11, 19, 43));
        jTextFieldSearchSurname1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldSearchSurname1.setForeground(new java.awt.Color(111, 255, 233));
        jPanel2.add(jTextFieldSearchSurname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 91, 206, -1));

        jTextFieldSearchName1.setBackground(new java.awt.Color(11, 19, 43));
        jTextFieldSearchName1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldSearchName1.setForeground(new java.awt.Color(111, 255, 233));
        jPanel2.add(jTextFieldSearchName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 51, 206, -1));

        jLabelSName5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSName5.setForeground(new java.awt.Color(111, 255, 233));
        jLabelSName5.setText("Pretraga:");
        jPanel2.add(jLabelSName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 26, -1, -1));

        jLabelSName8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSName8.setForeground(new java.awt.Color(111, 255, 233));
        jLabelSName8.setText("Ime:");
        jPanel2.add(jLabelSName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 58, -1, -1));

        jLabelSName7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSName7.setForeground(new java.awt.Color(111, 255, 233));
        jLabelSName7.setText("Prezime:");
        jPanel2.add(jLabelSName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 98, -1, -1));

        jMenu1.setText("Odabir");

        jMenuItem1.setText("Studenti");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Dodaj studenta");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Natječaji");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Dodaj Natječaj");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // UPDATE
    
    public ImageIcon resizePic(String picPath){
        
        ImageIcon myImg = new ImageIcon(picPath);
        Image img = myImg.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon myPicture = new ImageIcon(img);
        return myPicture;
    }

    
    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
         JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        // file extension
        FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("*.Images", "jpg","png","gif");
        file.addChoosableFileFilter(fileFilter);
        
        int fileState = file.showSaveDialog(null);
        
        // if the user select a file 
        if(fileState == JFileChooser.APPROVE_OPTION){
            
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            ImageIcon resized = resizePic(path);
            imagePath = path;
            // display the image in the jlabel
            jLabel1.setIcon(resized);
            
        }
        else if(fileState == JFileChooser.CANCEL_OPTION){
            System.out.println("No image Selected");
        }
        
        
    }
    
    
    
     void updateStudenta() {
         boolean image = false;
         String ime =jTextField1.getText() ;
        student student = new student();
        student.setId(Integer.valueOf(jTextField6.getText()));
        student.setIme(jTextField1.getText());
        student.setPrezime(jTextField2.getText());
        student.setAdresa(jTextField3.getText());
        student.setFakultet(jTextField4.getText());   
        java.sql.Date date = java.sql.Date.valueOf(jTextField5.getText()); //where date is of pattern "yyyy-MM-dd"
        student.setDat_rod(date);
        if (imagePath != null){
            byte[] img = null;
            try {

                Path pth = Paths.get(imagePath);
                img = Files.readAllBytes(pth);
                student.setSlika(img);
                image = true;
            } catch (FileNotFoundException ex) {
                Logger.getLogger(addStudent.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(addStudent.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            image = false;
        }       
        student.setGodina(jComboBox1.getSelectedIndex());
        
            
        if (db.updateStudent(student,image)) {
                String timestamp = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss").format(LocalDateTime.now());
                jTextArea1.setText("Podaci o studentu " + ime + ",vrijeme: " + timestamp + " ,uspješno su spremljeni u bazu!");
                populateJTable();
                } else {
                jTextArea1.setText("Pogreška kod upisa podataka!");
        }
            //InputStream img = new FileInputStream(new File(imagePath));
            
            //  student.setSlika(img);
        

    }
     
      void deleteStudenta() {
         boolean image = false;
        student student = new student();
        student.setId(Integer.valueOf(jTextField6.getText()));
            
        if (db.deleteStudent(student)) {
                jTextArea1.setText("Student izbrisan!");
                populateJTable();
                clearFields();
                } else {
                jTextArea1.setText("Pogreška kod brisanja podataka!");
        }
            //InputStream img = new FileInputStream(new File(imagePath));
            
            //  student.setSlika(img);
        

    }
     
     
    
    
     
    // SELECT
    
    // Students table
    public void populateJTable(){
        ArrayList<student> stuList = new ArrayList<student>();
        stuList = db.studentList();
        String[] colNames = {"ID","Ime","Prezime","Adresa","Godina","Datum Rođenja","Fakultet","Slika"};
        Object[][] rows = new Object[stuList.size()][8];
        
        for(int i = 0; i< stuList.size();i++){
            rows[i][0] = stuList.get(i).getId();
            rows[i][1] = stuList.get(i).getIme();
            rows[i][2] = stuList.get(i).getPrezime();
            rows[i][3] = stuList.get(i).getAdresa();
            rows[i][4] = stuList.get(i).getGodina();
            rows[i][5] = stuList.get(i).getDat_rod();
            rows[i][6] = stuList.get(i).getFakultet();
            
            
            ImageIcon pic = new ImageIcon(new ImageIcon(stuList.get(i).getSlika()).
                    getImage()
                    .getScaledInstance(120,80,Image.SCALE_SMOOTH));
            rows[i][7] = pic;
        }
        Images imgs = new Images(rows,colNames);
        jTable1.setModel(imgs);
        jTable1.setRowHeight(80);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(150);
    }
    
    
    private void jLabelClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelClose1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        // Display selected row data
        
        
        // Get selected row index
        int rowIndex = jTable1.getSelectedRow();
        String godina = jTable1.getValueAt(rowIndex, 4).toString();
        int god = Integer.valueOf(godina);
        jTextField1.setText(jTable1.getValueAt(rowIndex, 1).toString());
        jTextField2.setText(jTable1.getValueAt(rowIndex, 2).toString());
        jTextField3.setText(jTable1.getValueAt(rowIndex, 3).toString());
        jTextField4.setText(jTable1.getValueAt(rowIndex, 6).toString());
        jTextField5.setText(jTable1.getValueAt(rowIndex, 5).toString());
        jTextField6.setText(jTable1.getValueAt(rowIndex, 0).toString());
        jComboBox1.setSelectedIndex(god);
        
        Image pic = ((ImageIcon)jTable1.getValueAt(rowIndex, 7)).getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img = new ImageIcon(pic);
        jLabel1.setIcon(img);
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jTable1.getSelectionModel().isSelectionEmpty()){
            clearFields();
            error("Nije odabran ni jedan student");
            return;
        }
        if(jTextField6.getText().isEmpty()){
            error("Niste odabrali kojem studentu želite pridružiti novu sliku!");
            return;
        }
         JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        // file extension
        FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("*.Images", "jpg","png","gif");
        file.addChoosableFileFilter(fileFilter);
        
        int fileState = file.showSaveDialog(null);
        
        // if the user select a file 
        if(fileState == JFileChooser.APPROVE_OPTION){
            
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            ImageIcon resized = resizePic(path);
            imagePath = path;
            // display the image in the jlabel
            jLabel1.setIcon(resized);
            
        }
        else if(fileState == JFileChooser.CANCEL_OPTION){
            System.out.println("No image Selected");
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectionModel().isSelectionEmpty()){
            clearFields();
            error("Nije odabran ni jedan student");
            return;
        }
        if(checkFields() != null){
            error("Niste odabrali studenta za promjene!");
            return;
        }
        if(!validateDate(jTextField5.getText())){
             error("Format datuma nije valjan");
             return;
        } 
        if(imagePath != null){
            if(!validateImg(imagePath)){
            error("Postavljena datoteka nije slika!");
            return;
            }   
        }
        updateStudenta();
        clearFields();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectionModel().isSelectionEmpty()){
            clearFields();
            error("Nije odabran ni jedan student");
            return;
        }
        if(jTextField6.getText() == null){
            error("Niste odabrali kojeg studenta želite obrisati");
            return;
        }
        deleteStudenta();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        allScholarships as = new allScholarships();
        as.setVisible(true);
        as.pack();
        as.setLocationRelativeTo(null);
        as.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        addScolarship as = new addScolarship();
        as.setVisible(true);
        as.pack();
        as.setLocationRelativeTo(null);
        as.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        addStudent as = new addStudent();
        as.setVisible(true);
        as.pack();
        as.setLocationRelativeTo(null);
        as.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

         searchStudents();
        

        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        if(jComboBox2.getSelectedIndex()== 0){
            jButton6.setEnabled(false);
            populateJTable();
            jTextFieldSearchSurname1.setText("");
            jTextFieldSearchName1.setText("");
        }
        if(jComboBox2.getSelectedIndex() == 1){
            jTextFieldSearchName1.setEditable(true);
            jTextFieldSearchSurname1.setEditable(false);
            jTextFieldSearchSurname1.setText("");
            jButton6.setEnabled(true);
        }
        if(jComboBox2.getSelectedIndex() == 2){
            jTextFieldSearchName1.setEditable(false);
            jTextFieldSearchSurname1.setEditable(true);
            jTextFieldSearchName1.setText("");
            jButton6.setEnabled(true);
        }
        if(jComboBox2.getSelectedIndex() == 3){
            jTextFieldSearchName1.setEditable(true);
            jTextFieldSearchSurname1.setEditable(true);
            jButton6.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    
    
    void error(String msg) {
        Object[] options = {
            "U redu"};
        int i = JOptionPane.showOptionDialog(this, msg,
                "  - Upozorenje -  ",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE, null,
                options, options[0]);
    }
    
    String checkFields(){
        String msg;
        if(jTextField1.getText().isEmpty()){
            msg = "Niste unjeli ime!";
            return msg;
        }
        else if(jTextField2.getText().isEmpty()){
            msg = "Niste unjeli prezime!";
            return msg;
        }
        else if(jTextField3.getText().isEmpty()){
            msg = "Niste unjeli adresu!";
            return msg;
        }
        else if(jTextField4.getText().isEmpty()){
            msg = "Niste unjeli fakultet!";
            return msg;
        }
        else if(jTextField5.getText().isEmpty()){
            msg = "Niste unjeli datum rođenja!";
            return msg;
        }
        else if(jComboBox1.getSelectedIndex() == 0){
            msg = "Niste odabrali godinu!";
            return msg;
        }
        
        else{
            return null;
        }
    }
    
    
    
    public static boolean validateDate(String dateString){
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    sdf.setLenient(false);
    try {
        sdf.parse(dateString);
        return true;
    } catch (ParseException ex) {
        return false;
        }
    }
    
    public boolean validateImg(String imagePath){
        File f = new File(imagePath);
        MimetypesFileTypeMap mftp = new MimetypesFileTypeMap();
        mftp.addMimeTypes("image png jpg jpeg");
        String mimeType = mftp.getContentType(f).split("/")[0];
        if(mimeType.equals("image")){
            return true;
        }
        else{
            return false;
        }
    }
    
    public void clearFields(){
        
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jComboBox1.setSelectedIndex(0);
        jLabel1.setIcon(null);
    }
    
    void searchStudents(){
        
       
         String send;
         if(jComboBox2.getSelectedIndex() == 1){
             send = jTextFieldSearchName1.getText();
         }
         else if(jComboBox2.getSelectedIndex() == 2){
             send = jTextFieldSearchSurname1.getText();
         }
         else{
             send = jTextFieldSearchName1.getText() +","+ jTextFieldSearchSurname1.getText();
         }
        ArrayList<student> stuList = new ArrayList<student>();
        stuList = db.studentSearch(send,jComboBox2.getSelectedIndex());
        String[] colNames = {"ID","Ime","Prezime","Adresa","Godina","Datum Rođenja","Fakultet","Slika"};
        Object[][] rows = new Object[stuList.size()][8];
        
        for(int i = 0; i< stuList.size();i++){
            rows[i][0] = stuList.get(i).getId();
            rows[i][1] = stuList.get(i).getIme();
            rows[i][2] = stuList.get(i).getPrezime();
            rows[i][3] = stuList.get(i).getAdresa();
            rows[i][4] = stuList.get(i).getGodina();
            rows[i][5] = stuList.get(i).getDat_rod();
            rows[i][6] = stuList.get(i).getFakultet();
            
            
            ImageIcon pic = new ImageIcon(new ImageIcon(stuList.get(i).getSlika()).
                    getImage()
                    .getScaledInstance(120,80,Image.SCALE_SMOOTH));
            rows[i][7] = pic;
        }
        Images imgs = new Images(rows,colNames);
        jTable1.setModel(imgs);
        jTable1.setRowHeight(80);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(150);
    
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(allStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(allStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(allStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(allStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new allStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose1;
    private javax.swing.JLabel jLabelSName5;
    private javax.swing.JLabel jLabelSName7;
    private javax.swing.JLabel jLabelSName8;
    private javax.swing.JLabel jLabelUserPic;
    public javax.swing.JLabel jLabelUsername;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    public javax.swing.JTextField jTextFieldSearchName1;
    public javax.swing.JTextField jTextFieldSearchSurname1;
    // End of variables declaration//GEN-END:variables
}
