
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC Master Race
 */
public class connectStudents extends javax.swing.JFrame {

    
    public java.sql.Connection veza;
    database db;
    String imagePath = null;
    private static int cap;
    private static String id;

    /**
     * Creates new form connectStudents
     */
    public connectStudents() {
        initComponents();     
        connectStudents.id = String.valueOf(id);
        this.setLocationRelativeTo(null);
        db = new database();
        db.initConnection_MySQL();
        populateJTable();
        Color greenish = new Color(111,255,233);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(greenish);
        jTable1.setSelectionBackground(Color.lightGray);
        if(jComboBox1.getSelectedIndex()== 0){
            jButton4.setEnabled(false);
        }
        if(jComboBox2.getSelectedIndex()== 0){
            jButton6.setEnabled(false);
        }
        JTableHeader th = jTable1.getTableHeader();       
        th.setForeground(Color.BLACK);  
        
        th.setFont(new Font("Tahoma",Font.PLAIN,16) {
        });
        
        
        jTable2.setShowGrid(true);
        jTable2.setGridColor(Color.RED);
        jTable2.setSelectionBackground(Color.lightGray);
        jTable2.setFont(new Font("Monaco", Font.BOLD, 20));
        
        JTableHeader th1 = jTable2.getTableHeader();       
        th1.setForeground(Color.BLACK);  
        
        th1.setFont(new Font("Tahoma",Font.PLAIN,16) {
        });
    }
    
    
    
    
    public connectStudents(int id1,int cap){
        initComponents();     
        connectStudents.id = String.valueOf(id1);
        connectStudents.cap = cap;
        this.setLocationRelativeTo(null);
        db = new database();
        db.initConnection_MySQL();
        populateJTable();
        populateJTable2();
        Color greenish = new Color(111,255,233);
        int freeSpace = -1;
        jTable1.setShowGrid(true);
        jTable1.setGridColor(greenish);
        jTable1.setSelectionBackground(Color.lightGray);
        jTable1.setFont(new Font("Monaco", Font.BOLD, 15));
        if(jComboBox1.getSelectedIndex()== 0){
            jButton4.setEnabled(false);
        }
        if(jComboBox2.getSelectedIndex()== 0){
            jButton6.setEnabled(false);
        }
        try {
            int taken = db.scolarshipNumber(id1);
            freeSpace = cap - taken;
        } catch (SQLException ex) {
            Logger.getLogger(connectStudents.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextFieldCapFree.setText(String.valueOf(freeSpace));
        
        JTableHeader th = jTable1.getTableHeader();       
        th.setForeground(Color.BLACK);  
        
        th.setFont(new Font("Tahoma",Font.PLAIN,16) {
        });
        
        
        jTable2.setShowGrid(true);
        jTable2.setGridColor(greenish);
        jTable2.setSelectionBackground(Color.lightGray);
        jTable2.setFont(new Font("Monaco", Font.BOLD, 15));
        
        JTableHeader th1 = jTable2.getTableHeader();       
        th1.setForeground(Color.BLACK);  
        
        th1.setFont(new Font("Tahoma",Font.PLAIN,16) {
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelClose1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelUserPic = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelSName7 = new javax.swing.JLabel();
        jLabelSName10 = new javax.swing.JLabel();
        jLabelSName4 = new javax.swing.JLabel();
        jTextFieldSearchSurname2 = new javax.swing.JTextField();
        jLabelSName5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextFieldSearchName2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabelSName9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextFieldSearchSurname1 = new javax.swing.JTextField();
        jLabelSName6 = new javax.swing.JLabel();
        jTextFieldSearchName1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabelSName1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabelSName8 = new javax.swing.JLabel();
        jTextFieldCap = new javax.swing.JTextField();
        jLabelSName = new javax.swing.JLabel();
        jLabelSName2 = new javax.swing.JLabel();
        jTextFieldSName = new javax.swing.JTextField();
        jLabelSName3 = new javax.swing.JLabel();
        jTextFieldCapFree = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(58, 80, 107));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(11, 19, 43));

        jLabelClose1.setBackground(new java.awt.Color(111, 255, 233));
        jLabelClose1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelClose1.setForeground(new java.awt.Color(111, 255, 233));
        jLabelClose1.setText("X");
        jLabelClose1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose1MouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(111, 255, 233));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(111, 255, 233));
        jLabel4.setText("UPRAVLJANJE STIPENDIJAMA");

        jLabel5.setBackground(new java.awt.Color(111, 255, 233));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(111, 255, 233));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("-");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelUserPic, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(406, 406, 406)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose1)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClose1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelUserPic, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(58, 80, 107));
        jPanel2.setForeground(new java.awt.Color(58, 80, 107));

        jComboBox1.setBackground(new java.awt.Color(111, 255, 233));
        jComboBox1.setForeground(new java.awt.Color(11, 19, 43));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Svi studenti", "Ime", "Prezime", "Ime i Prezime" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabelSName7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSName7.setForeground(new java.awt.Color(111, 255, 233));
        jLabelSName7.setText("Prezime:");

        jLabelSName10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSName10.setForeground(new java.awt.Color(111, 255, 233));
        jLabelSName10.setText("Prezime:");

        jLabelSName4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSName4.setForeground(new java.awt.Color(111, 255, 233));
        jLabelSName4.setText("Popis studenata koji su na ovom natječaju:");

        jTextFieldSearchSurname2.setBackground(new java.awt.Color(11, 19, 43));
        jTextFieldSearchSurname2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldSearchSurname2.setForeground(new java.awt.Color(111, 255, 233));

        jLabelSName5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSName5.setForeground(new java.awt.Color(111, 255, 233));
        jLabelSName5.setText("Pretraga:");

        jComboBox2.setBackground(new java.awt.Color(111, 255, 233));
        jComboBox2.setForeground(new java.awt.Color(11, 19, 43));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Svi studenti", "Ime", "Prezime", "Ime i Prezime" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextFieldSearchName2.setBackground(new java.awt.Color(11, 19, 43));
        jTextFieldSearchName2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldSearchName2.setForeground(new java.awt.Color(111, 255, 233));

        jButton5.setBackground(new java.awt.Color(111, 255, 233));
        jButton5.setForeground(new java.awt.Color(60, 63, 65));
        jButton5.setText("OBRIŠI STUDENTA SA LISTE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(111, 255, 233));
        jButton3.setForeground(new java.awt.Color(60, 63, 65));
        jButton3.setText("DODAJ STUDENTA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabelSName9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSName9.setForeground(new java.awt.Color(111, 255, 233));
        jLabelSName9.setText("Ime:");

        jTable2.setBackground(new java.awt.Color(11, 19, 43));
        jTable2.setForeground(new java.awt.Color(111, 255, 233));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable2.setGridColor(new java.awt.Color(111, 255, 233));
        jTable2.setSelectionForeground(java.awt.Color.black);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jTextFieldSearchSurname1.setBackground(new java.awt.Color(11, 19, 43));
        jTextFieldSearchSurname1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldSearchSurname1.setForeground(new java.awt.Color(111, 255, 233));

        jLabelSName6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSName6.setForeground(new java.awt.Color(111, 255, 233));
        jLabelSName6.setText("Pretraga:");

        jTextFieldSearchName1.setBackground(new java.awt.Color(11, 19, 43));
        jTextFieldSearchName1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldSearchName1.setForeground(new java.awt.Color(111, 255, 233));

        jButton6.setBackground(new java.awt.Color(111, 255, 233));
        jButton6.setForeground(new java.awt.Color(60, 63, 65));
        jButton6.setText("PRETRAGA");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabelSName1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSName1.setForeground(new java.awt.Color(111, 255, 233));
        jLabelSName1.setText("Popis studenata koji nisu na ovom natječaju:");

        jTable1.setBackground(new java.awt.Color(11, 19, 43));
        jTable1.setForeground(new java.awt.Color(111, 255, 233));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(111, 255, 233));
        jTable1.setSelectionForeground(java.awt.Color.black);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton4.setBackground(new java.awt.Color(111, 255, 233));
        jButton4.setForeground(new java.awt.Color(60, 63, 65));
        jButton4.setText("PRETRAGA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabelSName8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSName8.setForeground(new java.awt.Color(111, 255, 233));
        jLabelSName8.setText("Ime:");

        jTextFieldCap.setEditable(false);
        jTextFieldCap.setBackground(new java.awt.Color(11, 19, 43));
        jTextFieldCap.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldCap.setForeground(new java.awt.Color(111, 255, 233));

        jLabelSName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelSName.setForeground(new java.awt.Color(111, 255, 233));
        jLabelSName.setText("Ime natječaja:");

        jLabelSName2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelSName2.setForeground(new java.awt.Color(111, 255, 233));
        jLabelSName2.setText("Preostala mjesta:");

        jTextFieldSName.setEditable(false);
        jTextFieldSName.setBackground(new java.awt.Color(11, 19, 43));
        jTextFieldSName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldSName.setForeground(new java.awt.Color(111, 255, 233));

        jLabelSName3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelSName3.setForeground(new java.awt.Color(111, 255, 233));
        jLabelSName3.setText("Kapacitet:");

        jTextFieldCapFree.setEditable(false);
        jTextFieldCapFree.setBackground(new java.awt.Color(11, 19, 43));
        jTextFieldCapFree.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldCapFree.setForeground(new java.awt.Color(111, 255, 233));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabelSName7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldSearchSurname1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelSName8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelSName5)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jTextFieldSearchName1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton4))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelSName1)
                                        .addGap(146, 146, 146)
                                        .addComponent(jButton3))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelSName9)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSName6)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextFieldSearchName2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton6))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelSName4)
                                        .addGap(100, 100, 100))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelSName10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldSearchSurname2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(115, 115, 115)))
                                .addComponent(jButton5))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelSName)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldSName, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabelSName3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCap, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelSName2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCapFree, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)))
                        .addGap(120, 120, 120)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelSName)
                        .addComponent(jTextFieldSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSName3)))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCapFree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSName2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldSearchSurname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSName7))
                                .addGap(35, 35, 35))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelSName5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldSearchName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSName8)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4))
                                .addGap(46, 46, 46)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelSName1)
                        .addGap(378, 378, 378))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelSName6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldSearchName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSName9)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldSearchSurname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSName10))
                                .addGap(8, 8, 8)
                                .addComponent(jLabelSName4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        jMenu1.setText("Odabir");

        jMenuItem1.setText("Studenti");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Dodaj studenta");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Natječaji");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Dodaj Natječaj");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelClose1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        // Get selected row index
        int rowIndex = jTable1.getSelectedRow();
        //jTextFieldName.setText(jTable1.getValueAt(rowIndex, 1).toString());
        //jTextFieldId.setText(jTable1.getValueAt(rowIndex, 0).toString());
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(Integer.parseInt(jTextFieldCapFree.getText()) == 0){
            error("Nema slobodnih mjesta za dodavanje studenata!");
            return;
        }
        // VALIDACIJA!!
            Dimension dim = new Dimension(1200,680);
           int id = Integer.valueOf(connectStudents.id);
           int cap = Integer.parseInt(jTextFieldCap.getText()); 
           String ime = jTextFieldSName.getText();       
           scolarshipStudentAdd ssa = new scolarshipStudentAdd(id,this.cap);
           ssa.setSize(dim);
           ssa.setVisible(true);
           ssa.pack();
           ssa.setLocationRelativeTo(null);
           
           ssa.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);       
           ssa.jTextFieldSName.setText(ime);
           
           

           this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int rowIndex = jTable2.getSelectedRow();
        //jTextFieldName.setText(jTable2.getValueAt(rowIndex, 1).toString());
        //jTextFieldId.setText(jTable2.getValueAt(rowIndex, 0).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(jTextFieldCapFree.getText()) == Integer.parseInt(jTextFieldCap.getText())  ){
            error("Nije moguće brisanje sa prazne liste!");
            return;
        }
           int id = Integer.valueOf(connectStudents.id);
           String ime = jTextFieldSName.getText();       
           scolarshipStudentRemove ssr = new scolarshipStudentRemove(id,this.cap);        
           ssr.setVisible(true);
           ssr.pack();
           ssr.setLocationRelativeTo(null);
           ssr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);       
           ssr.jTextFieldSName.setText(ime);
           

           this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        if(jTextFieldSearchName1.getText().isEmpty() && jComboBox1.getSelectedIndex() == 1){
            error("Niste upisali ime pod kojim pretražujete");
            return;
        }
        else if(jTextFieldSearchSurname1.getText().isEmpty() && jComboBox1.getSelectedIndex() == 2){
            error("Niste upisali prezime pod kojom pretražujete");
            return;
        }
        
        searchTableNotConnected();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        searchTableConnected();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex()== 0){
            jButton4.setEnabled(false);
            populateJTable();
            jTextFieldSearchSurname1.setText("");
            jTextFieldSearchName1.setText("");
        }
        if(jComboBox1.getSelectedIndex() == 1){
            jTextFieldSearchName1.setEditable(true);
            jTextFieldSearchSurname1.setEditable(false);
            jTextFieldSearchSurname1.setText("");
            jButton4.setEnabled(true);
        }
        if(jComboBox1.getSelectedIndex() == 2){
            jTextFieldSearchName1.setEditable(false);
            jTextFieldSearchSurname1.setEditable(true);
            jTextFieldSearchName1.setText("");
            jButton4.setEnabled(true);
        }
        if(jComboBox1.getSelectedIndex() == 3){
            jTextFieldSearchName1.setEditable(true);
            jTextFieldSearchSurname1.setEditable(true);
            jButton4.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        
         // TODO add your handling code here:
        if(jComboBox2.getSelectedIndex()== 0){
            jButton6.setEnabled(false);
            populateJTable2();
            jTextFieldSearchSurname2.setText("");
            jTextFieldSearchName2.setText("");
        }
        if(jComboBox2.getSelectedIndex() == 1){
            jTextFieldSearchName2.setEditable(true);
            jTextFieldSearchSurname2.setEditable(false);
            jTextFieldSearchSurname2.setText("");
            jButton6.setEnabled(true);
        }
        if(jComboBox2.getSelectedIndex() == 2){
            jTextFieldSearchName2.setEditable(false);
            jTextFieldSearchSurname2.setEditable(true);
            jTextFieldSearchName2.setText("");
            jButton6.setEnabled(true);
        }
        if(jComboBox2.getSelectedIndex() == 3){
            jTextFieldSearchName2.setEditable(true);
            jTextFieldSearchSurname2.setEditable(true);
            jButton6.setEnabled(true);
        }
        
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        allStudents as = new allStudents();
        as.setVisible(true);
        as.pack();
        as.setLocationRelativeTo(null);
        as.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        addStudent as = new addStudent();
        as.setVisible(true);
        as.pack();
        as.setLocationRelativeTo(null);
        as.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        allScholarships as = new allScholarships();
        as.setVisible(true);
        as.pack();
        as.setLocationRelativeTo(null);
        as.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        addScolarship as = new addScolarship();
        as.setVisible(true);
        as.pack();
        as.setLocationRelativeTo(null);
        as.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    
    void error(String msg) {
        Object[] options = {
            "U redu"};
        int i = JOptionPane.showOptionDialog(this, msg,
                "  - Upozorenje -  ",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE, null,
                options, options[0]);
    }
    
    /*    
    
    
    void connectStudent() {
        int sId = Integer.valueOf(jTextFieldId.getText());
        int nId = Integer.valueOf(connectStudents.id);
        if (db.connectStudent(sId,nId)) {
                jTextArea1.setText("Student dodan u natječaj");
                populateJTable();
                } else {
                jTextArea1.setText("Pogreška kod upisa podataka!");
        }

    }
    
    
    void disconnectStudent(){
        int sId = Integer.valueOf(jTextFieldId.getText());
        int nId = Integer.valueOf(connectStudents.id);
        if (db.disconnectStudent(sId,nId)) {
                jTextArea1.setText("Student izbrisan iz liste natječaja");
                populateJTable();
                } else {
                jTextArea1.setText("Pogreška kod upisa podataka!");
        }
        
    }
    */
     // Students table
    public void populateJTable(){
        int sId = Integer.valueOf(id);
        ArrayList<student> stuList = new ArrayList<student>();
        stuList = db.studentList3(sId);
        String[] colNames = {"ID","Ime","Prezime","Adresa","Godina","Datum Rođenja","Fakultet","Slika"};
        Object[][] rows = new Object[stuList.size()][8];
        
        for(int i = 0; i< stuList.size();i++){
            rows[i][0] = stuList.get(i).getId();
            rows[i][1] = stuList.get(i).getIme();
            rows[i][2] = stuList.get(i).getPrezime();
            rows[i][3] = stuList.get(i).getAdresa();
            rows[i][4] = stuList.get(i).getGodina();
            rows[i][5] = stuList.get(i).getDat_rod();
            rows[i][6] = stuList.get(i).getFakultet();
            
            
            ImageIcon pic = new ImageIcon(new ImageIcon(stuList.get(i).getSlika()).
                    getImage()
                    .getScaledInstance(120,80,Image.SCALE_SMOOTH));
            rows[i][7] = pic;
        }
        Images imgs = new Images(rows,colNames);
        jTable1.setModel(imgs);
        jTable1.setRowHeight(80);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(150);
    }
    
    public void populateJTable2(){
        int nId = Integer.valueOf(connectStudents.id);
        ArrayList<student> stuList = new ArrayList<student>();
        stuList = db.studentList2(nId);
        String[] colNames = {"ID","Ime","Prezime","Adresa","Godina","Datum Rođenja","Fakultet","Slika"};
        Object[][] rows = new Object[stuList.size()][8];
        
        for(int i = 0; i< stuList.size();i++){
            rows[i][0] = stuList.get(i).getId();
            rows[i][1] = stuList.get(i).getIme();
            rows[i][2] = stuList.get(i).getPrezime();
            rows[i][3] = stuList.get(i).getAdresa();
            rows[i][4] = stuList.get(i).getGodina();
            rows[i][5] = stuList.get(i).getDat_rod();
            rows[i][6] = stuList.get(i).getFakultet();
            
            
            ImageIcon pic = new ImageIcon(new ImageIcon(stuList.get(i).getSlika()).
                    getImage()
                    .getScaledInstance(120,80,Image.SCALE_SMOOTH));
            rows[i][7] = pic;
        }
        Images imgs = new Images(rows,colNames);
        jTable2.setModel(imgs);
        jTable2.setRowHeight(80);
        jTable2.getColumnModel().getColumn(7).setPreferredWidth(150);
    }
    
    void searchTableConnected(){
         String send;
         int nId = Integer.valueOf(connectStudents.id);
         if(jComboBox2.getSelectedIndex() == 1){
             send = jTextFieldSearchName2.getText();
         }
         else if(jComboBox2.getSelectedIndex() == 2){
             send = jTextFieldSearchSurname2.getText();
         }
         else{
             send = jTextFieldSearchName2.getText() +","+ jTextFieldSearchSurname2.getText();
         }
         
        ArrayList<student> stuList = new ArrayList<student>();
        stuList = db.studentListConnectedSearch(nId,send,jComboBox2.getSelectedIndex());
        String[] colNames = {"ID","Ime","Prezime","Adresa","Godina","Datum Rođenja","Fakultet","Slika"};
        Object[][] rows = new Object[stuList.size()][8];
        
        for(int i = 0; i< stuList.size();i++){
            rows[i][0] = stuList.get(i).getId();
            rows[i][1] = stuList.get(i).getIme();
            rows[i][2] = stuList.get(i).getPrezime();
            rows[i][3] = stuList.get(i).getAdresa();
            rows[i][4] = stuList.get(i).getGodina();
            rows[i][5] = stuList.get(i).getDat_rod();
            rows[i][6] = stuList.get(i).getFakultet();
            
            
            ImageIcon pic = new ImageIcon(new ImageIcon(stuList.get(i).getSlika()).
                    getImage()
                    .getScaledInstance(120,80,Image.SCALE_SMOOTH));
            rows[i][7] = pic;
        }
        Images imgs = new Images(rows,colNames);
        jTable2.setModel(imgs);
        jTable2.setRowHeight(80);
        jTable2.getColumnModel().getColumn(7).setPreferredWidth(150);
    }
    
    
    void searchTableNotConnected(){
        String send;
         int nId = Integer.valueOf(connectStudents.id);
         if(jComboBox1.getSelectedIndex() == 1){
             send = jTextFieldSearchName1.getText();
         }
         else if(jComboBox1.getSelectedIndex() == 2){
             send = jTextFieldSearchSurname1.getText();
         }
         else{
             send = jTextFieldSearchName1.getText() +","+ jTextFieldSearchSurname1.getText();
         }
        ArrayList<student> stuList = new ArrayList<student>();
        stuList = db.studentListNotConnectedSearch(nId,send,jComboBox1.getSelectedIndex());
        String[] colNames = {"ID","Ime","Prezime","Adresa","Godina","Datum Rođenja","Fakultet","Slika"};
        Object[][] rows = new Object[stuList.size()][8];
        
        for(int i = 0; i< stuList.size();i++){
            rows[i][0] = stuList.get(i).getId();
            rows[i][1] = stuList.get(i).getIme();
            rows[i][2] = stuList.get(i).getPrezime();
            rows[i][3] = stuList.get(i).getAdresa();
            rows[i][4] = stuList.get(i).getGodina();
            rows[i][5] = stuList.get(i).getDat_rod();
            rows[i][6] = stuList.get(i).getFakultet();
            
            
            ImageIcon pic = new ImageIcon(new ImageIcon(stuList.get(i).getSlika()).
                    getImage()
                    .getScaledInstance(120,80,Image.SCALE_SMOOTH));
            rows[i][7] = pic;
        }
        Images imgs = new Images(rows,colNames);
        jTable1.setModel(imgs);
        jTable1.setRowHeight(80);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(150);
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(connectStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(connectStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(connectStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(connectStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new connectStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelClose1;
    private javax.swing.JLabel jLabelSName;
    private javax.swing.JLabel jLabelSName1;
    private javax.swing.JLabel jLabelSName10;
    private javax.swing.JLabel jLabelSName2;
    private javax.swing.JLabel jLabelSName3;
    private javax.swing.JLabel jLabelSName4;
    private javax.swing.JLabel jLabelSName5;
    private javax.swing.JLabel jLabelSName6;
    private javax.swing.JLabel jLabelSName7;
    private javax.swing.JLabel jLabelSName8;
    private javax.swing.JLabel jLabelSName9;
    private javax.swing.JLabel jLabelUserPic;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    public javax.swing.JTextField jTextFieldCap;
    public javax.swing.JTextField jTextFieldCapFree;
    public javax.swing.JTextField jTextFieldSName;
    public javax.swing.JTextField jTextFieldSearchName1;
    public javax.swing.JTextField jTextFieldSearchName2;
    public javax.swing.JTextField jTextFieldSearchSurname1;
    public javax.swing.JTextField jTextFieldSearchSurname2;
    // End of variables declaration//GEN-END:variables
}
